create table "users" ("name" VARCHAR NOT NULL PRIMARY KEY);
create table "tasks" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"user_name" VARCHAR NOT NULL,"task" VARCHAR NOT NULL);
alter table "tasks" add constraint "user_fk" foreign key("user_name") references "users"("name") on update RESTRICT on delete CASCADE;
